/**
 * Journal types — trading journal entries, snapshots, and tags.
 */

import { MarketArea } from './common';

/** A journal entry */
export interface JournalEntry {
  id: string;
  userId: string;
  /** Related trade ID (optional — can be a general note) */
  tradeId?: string;
  /** Related strategy ID */
  strategyId?: string;
  area?: MarketArea;
  /** Title */
  title: string;
  /** Markdown content */
  content: string;
  /** Emotional state when writing */
  mood?: JournalMood;
  /** Tags for filtering */
  tags: Tag[];
  /** Attached snapshots (charts, screenshots) */
  snapshots: TradeSnapshot[];
  /** Whether this was auto-generated */
  autoGenerated: boolean;
  /** AI analysis of the entry (optional) */
  aiAnalysis?: string;
  createdAt: string;
  updatedAt: string;
}

/** Mood tracking for psychological analysis */
export type JournalMood =
  | 'confident'
  | 'neutral'
  | 'anxious'
  | 'frustrated'
  | 'euphoric'
  | 'fearful'
  | 'disciplined'
  ;

/** A snapshot attached to a journal entry */
export interface TradeSnapshot {
  id: string;
  journalEntryId: string;
  /** Type of snapshot */
  type: SnapshotType;
  /** URL to the stored image/data */
  url: string;
  /** Description */
  caption?: string;
  /** Snapshot data (chart config, etc.) */
  data?: Record<string, unknown>;
  createdAt: string;
}

export type SnapshotType =
  | 'chart'         // Chart screenshot
  | 'screenshot'    // Manual screenshot
  | 'order_book'    // Order book snapshot
  | 'equity_curve'  // Equity curve at that moment
  ;

/** Tag for organizing journal entries */
export interface Tag {
  id: string;
  name: string;
  color: string;
  userId: string;
}
